=begin
Games API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def answers_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def games_id_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def games_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
