# Games API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# Generated by: https://github.com/openapitools/openapi-generator.git
#

class Incarnation < ApplicationRecord
  has_many :games, dependent: :destroy
  belongs_to :region
end
