language: elixir
elixir:
  - 1.4.2
before_install:
  - "rvm install ruby-2.1.8"
  - "rvm use 2.1.8"
  - "bundle install"
  # FIXME Creates an expected file excluded by .gitignore
  - "echo 'use Mix.Config\n\nconfig :adventure_registrations, nothing: 0' > config/dev.secret.exs"
before_script:
  - "phantomjs -w --webdriver-loglevel=ERROR &"
