update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push an internal testing build to TestFlight"
  lane :alpha do
    cocoapods
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
      distribute_external: true,
      groups: 'beta'
    )
  end
end
