// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEksCFF5TIYNJ22gF4jsRYSVFzLfX5HYY',
    appId: '1:134243646832:android:27a0f5528c9c39a9eda3b5',
    messagingSenderId: '134243646832',
    projectId: 'landgrab-notifications',
    storageBucket: 'landgrab-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kyuomLEBwvJKwtuGDaZw55FyCTYMeS8',
    appId: '1:134243646832:ios:46386dce1d7ba100eda3b5',
    messagingSenderId: '134243646832',
    projectId: 'landgrab-notifications',
    storageBucket: 'landgrab-notifications.firebasestorage.app',
    iosBundleId: 'ca.chromatin.poles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-kyuomLEBwvJKwtuGDaZw55FyCTYMeS8',
    appId: '1:134243646832:ios:0fb2587f3b599b95eda3b5',
    messagingSenderId: '134243646832',
    projectId: 'landgrab-notifications',
    storageBucket: 'landgrab-notifications.firebasestorage.app',
    iosBundleId: 'ca.chromatin.poles.poles',
  );
}
