/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.50.1
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPeriodV2010PeriodSafelist {
    /// The unique string that we created to identify the SafeList resource.
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The phone number in SafeList.
    #[serde(rename = "phone_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<Option<String>>,
}

impl ApiPeriodV2010PeriodSafelist {
    pub fn new() -> ApiPeriodV2010PeriodSafelist {
        ApiPeriodV2010PeriodSafelist {
            sid: None,
            phone_number: None,
        }
    }
}


