=begin
Games API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "answer".pluralize.to_sym, id: false do |t|
      t.String :id
      t.string :attributes
      t.string :relationships

      t.timestamps
    end

    create_table "answer_attributes".pluralize.to_sym, id: false do |t|
      t.string :answer
      t.boolean :correct

      t.timestamps
    end

    create_table "answer_input".pluralize.to_sym, id: false do |t|
      t.string :answer
      t.string :game

      t.timestamps
    end

    create_table "answer_relationships".pluralize.to_sym, id: false do |t|
      t.string :game

      t.timestamps
    end

    create_table "game".pluralize.to_sym, id: false do |t|
      t.String :id
      t.string :attributes
      t.string :relationships

      t.timestamps
    end

    create_table "game_attributes".pluralize.to_sym, id: false do |t|
      t.boolean :complete

      t.timestamps
    end

    create_table "game_input".pluralize.to_sym, id: false do |t|
      t.String :incarnation_id

      t.timestamps
    end

    create_table "game_relationships".pluralize.to_sym, id: false do |t|
      t.string :incarnation
      t.string :winner_answer

      t.timestamps
    end

    create_table "game_relationships_incarnation".pluralize.to_sym, id: false do |t|
      t.string :data

      t.timestamps
    end

    create_table "game_relationships_incarnation_data".pluralize.to_sym, id: false do |t|
      t.String :id

      t.timestamps
    end

    create_table "game_relationships_winner_answer".pluralize.to_sym, id: false do |t|
      t.string :data

      t.timestamps
    end

    create_table "game_relationships_winner_answer_data".pluralize.to_sym, id: false do |t|
      t.String :id

      t.timestamps
    end

    create_table "_games__id__get_200_response".pluralize.to_sym, id: false do |t|
      t.string :data
      t.string :included

      t.timestamps
    end

    create_table "_games__id__get_200_response_included_inner".pluralize.to_sym, id: false do |t|
      t.String :id
      t.string :attributes
      t.string :relationships

      t.timestamps
    end

    create_table "_games_post_201_response".pluralize.to_sym, id: false do |t|
      t.string :data
      t.string :included

      t.timestamps
    end

    create_table "_games_post_201_response_included_inner".pluralize.to_sym, id: false do |t|
      t.String :id
      t.string :attributes
      t.string :relationships

      t.timestamps
    end

    create_table "incarnation".pluralize.to_sym, id: false do |t|
      t.String :id
      t.string :attributes
      t.string :relationships

      t.timestamps
    end

    create_table "incarnation_attributes".pluralize.to_sym, id: false do |t|
      t.string :concept
      t.string :mask
      t.string :answer
      t.string :answers

      t.timestamps
    end

    create_table "incarnation_relationships".pluralize.to_sym, id: false do |t|
      t.string :region

      t.timestamps
    end

    create_table "region".pluralize.to_sym, id: false do |t|
      t.String :id
      t.string :attributes
      t.string :relationships

      t.timestamps
    end

    create_table "region_attributes".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :description

      t.timestamps
    end

    create_table "region_relationships".pluralize.to_sym, id: false do |t|
      t.string :parent

      t.timestamps
    end

  end
end
