[pure]
monitoring = "Your call may be recorded for quality assurance and training purposes."
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"
repeat_record_end = "Repeat, record an encouraging message for others, or end?"

silence = "We didn't hear anything."

phrase_not_found = "We couldn't find that cathartic phrase."
voicepass_not_found = "We couldn't find a team with that voicepass."

recordings = "What do you want to record? Prompts, regions, destinations"

character_name = "What character are you reading for?"
character_not_found = "Could not find that character. We heard this:"

prompt_sounds = "Here is how it sounds."
prompt_action = "Keep or rerecord?"

goodbye = "Good luck and goodbye!"

[remember]
ending = "Placeholder for ending message."

[testa]
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"

[testb]
welcome = "welcome test"
