[pure]
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"

[testa]
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"

[testb]
welcome = "welcome test"
