[pure]
monitoring = "Your call may be recorded for quality assurance and training purposes."
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"

silence = "We didn't hear anything."

phrase_not_found = "We couldn't find that cathartic phrase."
voicepass_not_found = "We couldn't find a team with that voicepass."

prompt_sounds = "Here is how it sounds."
prompt_action = "Keep or rerecord?"

[testa]
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"

[testb]
welcome = "welcome test"
