[pure]
monitoring = "Your call may be recorded for quality assurance and training purposes."
chromatin = "Thank you for calling Chromatin."

welcome = "welcome to unmnemonic devices"

voicemail_gather = "Leave a message for someone by saying their name."

voicepass = "what is your voice password?"
voicepass_confirm = "Is this correct?"

excerpt_gather = "Confirmed. What is your cathartic phrase or the collation of the findings from your kinetic instructions?"

repeat_record_end = "Repeat, record an encouraging message for others, or end?"

encouraging = "Here as an encouraging message from another team."

silence = "We didn't hear anything."

phrase_not_found = "We couldn't find that cathartic phrase."
voicepass_not_found = "We couldn't find a team with that voicepass."

recordings = "What do you want to record? Prompts, regions, destinations, teams"

character_name = "What character are you reading for?"
character_not_found = "Could not find that character. We heard this:"

prompt_sounds = "Here is how it sounds."
prompt_action = "Save or rerecord?"

goodbye = "Good luck and goodbye!"

voicemail_complete = "Thank you for your message."

[knut]
voicemail = "Hello, you've reached knut, please leave me a message."

[remember]
voicepass = "Who are you? We need your voicepass to know we can trust you."
voicepass_success = "Thank you for being willing to remember."
voicepass_not_found = "We have never heard of you."
silence = "We didn't hear anything."

voicemail = "Placeholder for shifting remember message."

ending_early = "Chromatin didn't have much of an ending planned for this as you're supposed to wander off in a blissful daze, wholly ignorant of any continuing strife around you. So much for that idea."
ending = "Placeholder for ending message."

[other]
ending_early_sound = "Placeholder for ending early sound."

[testa]
welcome = "welcome to unmnemonic devices"
voicepass = "what is your voice password?"

[testb]
welcome = "welcome test"
