name: Gathering checks

on:
  push:
  pull_request:
    paths:
      - "gathering/**"

permissions:
  checks: write
  pull-requests: write

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          package_json_file: gathering/package.json
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          cache-dependency-path: gathering/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
        working-directory: gathering
      - name: Lint
        run: pnpm lint
        working-directory: gathering

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          package_json_file: gathering/package.json
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
          cache-dependency-path: gathering/pnpm-lock.yaml
      - name: Install Dependencies
        run: pnpm install
        working-directory: gathering
      - name: Run Tests
        run: pnpm test
        working-directory: gathering
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: always()
        with:
          check_name: "Gathering test results"
          junit_files: junit/host.xml
