name: Gathering checks

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        working-directory: gathering
        with:
          node-version: 16.x
          cache: npm
      - name: Install Dependencies
        run: npm ci
        working-directory: gathering
      - name: Lint JS
        run: npm run lint:js
        working-directory: gathering
      - name: Lint HBS
        run: npm run lint:hbs
        working-directory: gathering

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
        working-directory: gathering
      - name: Install Dependencies
        run: npm ci
        working-directory: gathering
      - name: Run Tests
        run: npm test
        working-directory: gathering
