name: Gathering checks

on: [push, pull_request]

permissions:
  checks: write
  pull-requests: write

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: gathering/package-lock.json
      - name: Install Dependencies
        run: npm ci
        working-directory: gathering
      - name: Lint JS
        run: npm run lint:js
        working-directory: gathering
      - name: Lint HBS
        run: npm run lint:hbs
        working-directory: gathering

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: gathering/package-lock.json
      - name: Install Dependencies
        run: npm ci
        working-directory: gathering
      - name: Run Tests
        run: npm test
        working-directory: gathering
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: always()
        with:
          check_name: "Gathering test results"
          junit_files: junit/host.xml
