name: landgrab_app checks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "landgrab_app/**"
      - ".github/workflows/ci-landgrab-app.yml"

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Create asset file declared in pubspec but gitignored
      - run: touch .env.local
        working-directory: landgrab_app

      - run: flutter pub get
        working-directory: landgrab_app

      - run: flutter analyze
        working-directory: landgrab_app

      - run: flutter test
        working-directory: landgrab_app
