name: unmnemonic devices checks

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.7.0-alpha.2
  SQLX_FEATURES: "rustls,postgres"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - name: Set up database
        run: psql -f unmnemonic_devices_vrs/tests/api/fixtures/schema.sql postgres://postgres:postgres@localhost:5432/postgres
      - uses: dtolnay/rust-toolchain@1.68.2
      - uses: Swatinem/rust-cache@v2
      - name: Set up env
        run: export $(cat .env.test | xargs)
      - name: Run tests
        working-directory: unmnemonic_devices_vrs
        run: cargo test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.68.2
        with:
          components: rustfmt
      - name: Enforce formatting
        working-directory: unmnemonic_devices_vrs
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - name: Set up database
        run: psql -f unmnemonic_devices_vrs/tests/api/fixtures/schema.sql postgres://postgres:postgres@localhost:5432/postgres
      - uses: dtolnay/rust-toolchain@1.68.2
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        working-directory: unmnemonic_devices_vrs
        run: cargo clippy -- -D warnings
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up database
        run: psql -f unmnemonic_devices_vrs/tests/api/fixtures/schema.sql postgres://postgres:postgres@localhost:5432/postgres
      - uses: dtolnay/rust-toolchain@1.68.2
      - name: Install postgresql-client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-${{ env.SQLX_VERSION }}
      - name: Install sqlx-cli
        run: cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - name: Set up env
        run: export $(cat .env.test | xargs)
      - name: Generate code coverage
        working-directory: unmnemonic_devices_vrs
        run: cargo install cargo-tarpaulin@0.25.2 && cargo tarpaulin --verbose --workspace --out lcov --output-dir coverage
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost/postgres
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.1.2
