# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "waydowntown/waydowntown_server/**"
      - ".github/workflows/ci-waydowntown-server.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@713e0f1ab5cfaefd8883297722a07ab6d2e47305
        with:
          bundler-cache: true
          working-directory: waydowntown/waydowntown_server
      - name: Set up database schema
        working-directory: waydowntown/waydowntown_server
        run: bin/rails db:schema:load
      - name: Run tests
        working-directory: waydowntown/waydowntown_server
        run: bin/rails spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@713e0f1ab5cfaefd8883297722a07ab6d2e47305
        with:
          bundler-cache: true
          working-directory: waydowntown/waydowntown_server
      - name: Security audit dependencies
        working-directory: waydowntown/waydowntown_server
        run: bin/bundler-audit --update
      - name: Security audit application code
        working-directory: waydowntown/waydowntown_server
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        working-directory: waydowntown/waydowntown_server
        run: bin/rubocop --parallel
